### ISSUE TITLE
Release of version 0.4.0 is missing some commits from groovy-devel

### ISSUE THREAD

**Issue by bulwahn** [ros/ros_tutorials#11]
Probably due to some branch confusion, some commits from 0.3.13 were dropped in version 0.4.0. I believe that the commits

66bd5c8dcb35c50612b5bd26d82e9c1113dae544
1e559b3f811a6cf3daac59088d6d86ca1d31b261
d75909cfceac2a78d27aac240ed759220abaccd2
a7de3a75f4df0433186639f113dcd13f45f542f6

from Dirk Thomas should be rebased to hydro-devel and a new version with these commits should be released.

Especially, commit "check for CATKIN_ENABLE_TESTING" is important for the OpenEmbedded integration with meta-ros (github.vom/bmwcarit/meta-ros).

**Comment by tfoote** [comment]
I somehow failed to cherry-pick those commits when I forked.  They're in 0.4.1 now.
