### ISSUE TITLE
Turtle_teleop_key uses an inordinate amount of CPU

### ISSUE THREAD

**Issue by mjeronimo** [ros/ros_tutorials#119]
Ubuntu 20.04
ROS 2 Rolling

Execute 'ros2 run turtlesim turtle_teleop_key' and view using 'top'. CPU utilization is very high. Reading the keyboard should be done in a more efficient manner.

**Comment by sloretz** [comment]
I see the same behavior - about 25% to 27% CPU as reported by `top`. The CPU usage seems the same whether I'm pressing keys or not.

**Comment by clalancette** [comment]
This was fixed by #121, so closing.
