### ISSUE TITLE
turtlesim does not install .svg images

### ISSUE THREAD

**Issue by paulvarnell** [ros/ros_tutorials#12]
Turtlesim uses both .png and .svg images for turtles (currently the only .svg image is "hydro.svg"), but the cmake file only installs the .png images. The result of this is that occasionally a spawned turtle will not appear on screen.

In  turtlesim/CMakeLists.txt, the lines

``` cmake
install(DIRECTORY images
  DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION}
  FILES_MATCHING PATTERN "*.png")
```

should be changed to 

``` cmake
install(DIRECTORY images
  DESTINATION ${CATKIN_PACKAGE_SHARE_DESTINATION}
  FILES_MATCHING PATTERN "*.png" PATTERN "*.svg")
```

**Comment by dirk-thomas** [comment]
Thanks for the report. Fixed and released.
