### ISSUE TITLE
Missing rolling-devel branch

### ISSUE THREAD

**Issue by hidmic** [ros/ros_tutorials#120]
There's a tutorial in Rolling that expects the `rolling-devel` branch to exist here, but there's none. We could drop that reference, but should there be a `rolling-devel` branch? I see no `master` nor `ros2` branch either. It appears we've been creating distro specific branches as we go here (e.g. see #100).

**Comment by hidmic** [comment]
FYI @sloretz.

**Comment by sloretz** [comment]
I'd be fine with any of `rolling-devel`, `master` or `main`. @mabelzhang Any preferences on branch name?

**Comment by mabelzhang** [comment]
`rolling-devel` or `main` or `ros2` is fine. For an external contributor, maybe `ros2` is the most intuitive to create PRs? `main` could be ambiguous whether it's ROS 1 or 2.

**Comment by hidmic** [comment]
> For an external contributor, maybe `ros2` is the most intuitive to create PRs

Don't have a strong opinion. But I do think we need to branch and get that tutorial fixed.

**Comment by mabelzhang** [comment]
Looks like the one in common above is `rolling-devel`, which is also the expected branch. Feel free to create it -- or I can do that if you want. I guess it'd branch off of `galactic-devel`?

**Comment by hidmic** [comment]
Just added `rolling-devel`, branching off of `galactic-devel`.
