### ISSUE TITLE
Running roscore on ev3

### ISSUE THREAD

**Issue by ariharasudhanm** [ros/ros_tutorials#139]
Could you able to run roscore on the ev3? because I'm facing a lot of issues.

**Comment by audrow** [comment]
Hi @ariharasudhanm, I'm not sure this is the right place for this. Questions generally go to [ROS Answers](https://answers.ros.org/questions/) or the [Robotics Stack Exchange](https://robotics.stackexchange.com/). I think you'll have better luck there. Also, when you ask there, it would be helpful to give more context. Good luck!
