### ISSUE TITLE
turtlesim does not clean up its parameters when it terminates

### ISSUE THREAD

**Issue by jihoonl** [ros/ros_tutorials#16]
I noticed turtlesim_node sets background_r,g,b rosparam when it starts 
but it does not deletes it when it dies.

**Comment by dirk-thomas** [comment]
Parameters are conceptionally not being unset when the node which sets them goes away. There is no expectation that parameters are cleaned up by a node either.

`turtlesim` could set the rgb values to defined values when it starts up. But I would consider that syntactic sugar for this tutorial application. It could actually be considered a good example for the user that the parameters actually stay as they are to demomstrate the persistence of the parameters until the master is restarted.

Therefore I will mark this ticket as "wontfix". Please feel free to comment on the ticket even after it has been closed.

**Comment by jihoonl** [comment]
Ok. Thanks for answer.
