### ISSUE TITLE
Wrong documentation, turtlesim mimic subscribed to turtlesim/pose instead of cmd_vel

### ISSUE THREAD

**Issue by AlpNov** [ros/ros_tutorials#26]
According to this documentation http://wiki.ros.org/turtlesim#mimic, mimic subscribes to the cmd_vel topic of the turtle to be mimicked, instead of pose which is what the source code shows according to this source code: https://github.com/ros/ros_tutorials/blob/jade-devel/turtlesim/tutorials/mimic.cpp

Suggest to change the documentation in ros wiki to reflect the actual working of the program

**Comment by dirk-thomas** [comment]
Thank you for paying attention to details. I have updated the wiki page accordingly: http://wiki.ros.org/action/diff/turtlesim?action=diff&rev1=41&rev2=42

In the future please feel free to edit the wiki page directly if you are confident about the change or propose a specific change using a ticket to get feedback before.
