### ISSUE TITLE
turtlesim does not shut down correctly

### ISSUE THREAD

**Issue by chadrockey** [ros/ros_tutorials#3]
For this tutorial:
http://www.ros.org/wiki/ROS/Tutorials/UnderstandingNodes

Turtlesim doesn't seem to ctrl-c correctly and unassociate from the master, producing an error later on in the tutorial:

rosnode list
                /my_turtle
                /rosout
                /turtlesim

**Comment by dirk-thomas** [comment]
I can't reproduce the issue anymore. Likely it has been resolved with rospack 2.1.13 which removes wrongly installed signal handlers of the embedded Python interpreter.
