### ISSUE TITLE
turtlesim should use geometry_msgs/Twist and /cmd_vel

### ISSUE THREAD

**Issue by chadrockey** [ros/ros_tutorials#4]
In this tutorial:
http://www.ros.org/wiki/ROS/Tutorials/UnderstandingTopics

We seem to suggest that robots should implement their own command message (turtlesim/Velocity).  That's not correct, so we should show have turtlesim use /cmd_vel topics and geometry_msgs/Twist as is truly standard.  Users often start their own software based on tutorials, so we need to make sure the tutorials follow standard practices.

**Comment by ahendrix** [comment]
+1

**Comment by dirk-thomas** [comment]
Either someone provides a complete patch to modify the code and the wiki accordingly or we should just add a note stating that to the existing tutorial.

**Comment by jihoonl** [comment]
@dirk-thomas I just requested pull request to use Twist msg. Would you check it?

**Comment by dirk-thomas** [comment]
Pull request #5

**Comment by dirk-thomas** [comment]
Would you also update the pull request to use the `cmd_vel` topic?

**Comment by jihoonl** [comment]
Change pushed.

**Comment by dirk-thomas** [comment]
The patch has been merged. The Wiki page must be updated but only after a new release is in the public repo.

**Comment by chadrockey** [comment]
For hydro right?  We don't want to risk that someone out there probably
depends on that message for their robot.... >:(

**Comment by dirk-thomas** [comment]
Merged #7
