### ISSUE TITLE
Angle wrapping in draw_square.cpp

### ISSUE THREAD

**Issue by jarvisschultz** [ros/ros_tutorials#43]
Now that [this commit](https://github.com/ros/ros_tutorials/commit/b1f84c4902a1263381b83f7c41cca5cdc3f918dc) has been merged, the turtlesim is guaranteed for its pose to always be in [-pi, pi). However, when [checking if the turtle has reached its goal](https://github.com/ros/ros_tutorials/blob/821a8ae33c6da1a70e21453392f6980380f670f8/turtlesim/tutorials/draw_square.cpp#L29-L32), a simple `fabs` is used. This results in the turtle never being able to complete its square as reported in [this answers.ros.org question](https://answers.ros.org/question/292653/turtlesims-draw_square-only-draws-34-of-the-square-like-_-and-then-it-spins-forever/).

A very easy fix was to include [angles](http://wiki.ros.org/angles) as a dependency and then use `angles::shortest_angular_distance`. If we are okay with modifying dependencies for this package, then I'd happily open a PR from [my fork](https://github.com/jarvisschultz/ros_tutorials/commit/9e6575fdaae59b637b4b44678d52964ae865b8da). We could, of course, also write a similar function inline if we didn't want to modify dependencies.

**Comment by dirk-thomas** [comment]
`angles` is not part of the ROS core metapackage and therefore `ros_tutorials` can't use it.

Please consider to propose a patch to the tutorial code which implements a similar function to perform the correct check.

**Comment by dirk-thomas** [comment]
Addressed by #46.
