### ISSUE TITLE
removal of velocity breaks all the downstream tutorial packages

### ISSUE THREAD

**Issue by tfoote** [ros/ros_tutorials#8]
403d4e792f6799c6c34f3d85548e441d1360c1e5  such as geometry_tutorials and common_tutorials. @jihoonl

**Comment by tfoote** [comment]
This should never have been released without fixing all those packages.

**Comment by jihoonl** [comment]
@tfoote  Hm... I did not know about it.  I have checked ros wiki 'Used By' to check dependencies in groovy. and there was only ros_tutorials. 

I agree that it should keep the api for fuerte and electric though.

**Comment by jihoonl** [comment]
Also it has not been released yet. I think Dirk plans to release it in hydro?

**Comment by jihoonl** [comment]
Ah it is in shadow-fixed..

**Comment by tfoote** [comment]
I have created hydro-devel with these changes integrated, and then reverted groovy-devel to not include them release 0.3.12.  It's building on the farm now.

**Comment by tfoote** [comment]
Ok, it's building again.
