### ISSUE TITLE
Wiki docs for turtlesim are out of date.

### ISSUE THREAD

**Issue by ahendrix** [ros/ros_tutorials#9]
The ROS node docs (and possibly others) on the main page of the wiki don't reflect the update from velocity to `geometry_msgs/Twist` in _Hydro_.

This probably needs to be updated in the doxygen files in the source.

**Comment by dirk-thomas** [comment]
Addressed in http://wiki.ros.org/turtlesim?action=diff&rev1=38&rev2=39
